name: CET6 Daily Checkin Automation
on:
  schedule:
    - cron: '0 20 * * *'  # UTC时间20:00 = 北京时间次日4:00
  workflow_dispatch: {}

permissions:
  issues: write
  repository-projects: write
  contents: write 

jobs:
  create-checkin-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Daily Checkin Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { graphql } = github
            try {
              // 1. 获取北京时间
              const now = new Date()
              const chinaTime = new Date(now.getTime() + (8 * 60 * 60 * 1000)) // UTC+8
              const chinaDate = chinaTime.toISOString().split('T')[0]
              const fullDateTime = chinaTime.toISOString() // 带时区的完整格式

              // 2. 创建Issue
              const issue = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `[CET6打卡] ${chinaDate}`,
                body: '请填写今日CET6进展：\n- [ ] 背单词\n- [ ] 听听力\n- [ ] 做真题',
                assignees: ['CuT-Shade'],
                labels: ['@6-提升计划'],
                milestone: 6
              })

              console.log('Issue created successfully:', issue.data.number)

              // 3. 获取项目ID和字段
              const projectQuery = await graphql(`
                query($login: String!, $number: Int!) {
                  user(login: $login) {
                    projectV2(number: $number) {
                      id
                      field(name: "Start date") {
                        ... on ProjectV2FieldCommon {
                          id
                          name
                        }
                      }
                      fields(first: 20) {
                        nodes {
                          ... on ProjectV2FieldCommon {
                            id
                            name
                            dataType
                          }
                        }
                      }
                    }
                  }
                }
              `, {
                login: 'CuT-Shade',
                number: 1
              });

              console.log('Project query result:', JSON.stringify(projectQuery, null, 2))

              const projectId = projectQuery.user.projectV2.id
              console.log('Project ID:', projectId)

              // 找到日期字段的ID
              const fields = projectQuery.user.projectV2.fields.nodes
              console.log('Available fields:', fields.map(f => ({ id: f.id, name: f.name, dataType: f.dataType })))

              // 4. 添加到Project并获取item ID
              const addToProjectResult = await graphql(`
                mutation($projectId: ID!, $contentId: ID!) {
                  addProjectV2ItemById(input: {
                    projectId: $projectId,
                    contentId: $contentId
                  }) {
                    item {
                      id
                    }
                  }
                }
              `, {
                projectId: projectId,
                contentId: issue.data.node_id
              })

              console.log('Add to project result:', JSON.stringify(addToProjectResult, null, 2))

              const itemId = addToProjectResult.addProjectV2ItemById.item.id
              console.log('Item ID:', itemId)

              // 找到开始日期和结束日期字段
              const startDateField = fields.find(f => f.name.toLowerCase().includes('start') && f.dataType === 'DATE')
              const endDateField = fields.find(f => f.name.toLowerCase().includes('end') && f.dataType === 'DATE')

              if (startDateField && endDateField) {
                // 5. 更新日期字段
                const updateResult = await graphql(`
                  mutation($projectId: ID!, $itemId: ID!, $date: Date!) {
                    setStartDate: updateProjectV2ItemFieldValue(input: {
                      projectId: $projectId
                      itemId: $itemId
                      fieldId: "${startDateField.id}"
                      value: { date: $date }
                    }) { clientMutationId }
                    
                    setEndDate: updateProjectV2ItemFieldValue(input: {
                      projectId: $projectId
                      itemId: $itemId
                      fieldId: "${endDateField.id}"
                      value: { date: $date }
                    }) { clientMutationId }
                  }
                `, {
                  projectId: projectId,
                  itemId: itemId,
                  date: chinaDate
                })

                console.log('Update fields result:', JSON.stringify(updateResult, null, 2))
              } else {
                console.log('Date fields not found. Available fields:', fields)
              }

            } catch (error) {
              console.error('Error details:', {
                message: error.message,
                stack: error.stack,
                data: error.data
              })
              core.setFailed(`Workflow failed: ${error.message}`)
            }
