name: Watch Workflow Changes and Trigger

on:
  # push:
  #   paths:
  #     - '.github/workflows/CET6_daily_checkin.yml'
  workflow_dispatch: {}

jobs:
  trigger-daily-checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Daily Checkin Workflow
        uses: actions/github-script@v6
        with:
          script: |
            console.log("准备触发 daily-checkin.yml...");

            try {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: "daily-checkin.yml",
                ref: context.payload.repository.default_branch || "main"
              });

              console.log("✅ 已成功触发 workflow！");
            } catch (error) {
              console.error("❌ 触发失败:", error.message);
              throw error;
            }
